
stages:
  - test
  - code

#sast:
#  stage: test
#include:
#  - template: Security/SAST.gitlab-ci.yml

standar:psr12:
  stage: code
  image: lorisleiva/laravel-docker
  script:
    - phpcs --standard=PSR12 --colors --extensions=php --ignore=*/vendor/*,*/node_modules/*,*/doc/*,*/docs/*,*/resources/*,*/Resources/*,*/public/*,*/storage/*,*/bootstrap/*,*/migrations/*,composer-setup.php --exclude=Generic.Files.LineLength ./